# Site settings
# title: Team Live Bad Ass
email: rgonz_76@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  <----Got questions? We got answers......maybe.
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://www.teamlivebadass.org" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
